'use strict';
(function(){
 const context=document.modelContext;if(!context?.registerTool)return;
 const lifecycle=new AbortController();window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
 const props={rate:{type:'integer',minimum:5,maximum:120},hold:{type:'integer',minimum:1,maximum:200},gain:{type:'number',minimum:-1,maximum:2},D:{type:'number',minimum:0,maximum:100},centering:{type:'number',minimum:0,maximum:40,description:'Restoring rate toward fixation center in inverse seconds. Default 10; zero restores free Brownian drift.'},size:{type:'number',minimum:3,maximum:15},contrast:{type:'number',minimum:0,maximum:1},orientation:{type:'string',enum:['right','up','left','down']},controller:{type:'string',enum:['ideal','frame']},matchMean:{type:'boolean'}};
 function object(input,allowed){if(!input||typeof input!=='object'||Array.isArray(input))throw Error('Expected an object');for(const key of Object.keys(input))if(!allowed.includes(key))throw Error('Unknown parameter: '+key);}
 function read(){const p=probePixel().p;return {settings:{...result.settings},timeMs:time,playing,probeArcmin:{...probe},responseView:view.response,colorScale:view.scale,dutyCycle:result.duty,flashCount:result.onsets.length,atCell:{input:valueAt('input',time,p),M:valueAt('M',time,p),P:valueAt('P',time,p)}};}
 function register(tool){try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(error=>console.warn('Optional simulation tool unavailable:',error.message));}catch(error){console.warn('Optional simulation tool unavailable:',error.message);}}
 register({name:'configure_aoslo_simulation',title:'Configure AOSLO simulation',description:'Update flash timing, stabilization gain, drift centering, or optotype settings and compute the synchronized 1 ms retinal/M/P movies. Gain 0 is natural slip, 1 stabilization, and 2 reversed slip. Returns after the visible plots update.',annotations:{readOnlyHint:false,untrustedContentHint:false},inputSchema:{type:'object',properties:props,additionalProperties:false,minProperties:1},async execute(input){object(input,Object.keys(props));if(!Object.keys(input).length)throw Error('Provide at least one parameter');const candidate={...settings,...input};MODEL.validate(candidate);if(!Number.isInteger(candidate.rate))throw Error('Rate must be an integer in Hz');if(typeof candidate.matchMean!=='boolean')throw Error('matchMean must be boolean');const snapshot={...candidate};return await new Promise((resolve,reject)=>{let timeout;function cleanup(){clearTimeout(timeout);document.removeEventListener('aoslo-ready',ready);document.removeEventListener('aoslo-error',error);}function ready(){cleanup();if(Object.keys(snapshot).some(key=>result.settings[key]!==snapshot[key]))reject(Error('Configuration was superseded by another change'));else resolve(read());}function error(e){cleanup();reject(Error(e.detail));}document.addEventListener('aoslo-ready',ready);document.addEventListener('aoslo-error',error);timeout=setTimeout(()=>{cleanup();reject(Error('Simulation did not finish in 60 seconds'));},60000);settings=candidate;renderControls();requestCompute(true);});}});
 register({name:'inspect_aoslo_frame',title:'Inspect AOSLO frame',description:'Pause and scrub to an exact millisecond, optionally select a retinal cell or change response/color views. Updates the visible movies, space-time cursor, and cell traces. Does not change the simulated trial.',annotations:{readOnlyHint:false,untrustedContentHint:false},inputSchema:{type:'object',properties:{timeMs:{type:'integer',minimum:0,maximum:1299},xArcmin:{type:'number',minimum:-11.85,maximum:11.85},yArcmin:{type:'number',minimum:-11.85,maximum:11.85},responseView:{type:'string',enum:['full','optotype']},colorScale:{type:'string',enum:['independent','shared']}},required:['timeMs'],additionalProperties:false},execute(input){object(input,['timeMs','xArcmin','yArcmin','responseView','colorScale']);if(!Number.isInteger(input.timeMs)||input.timeMs<0||input.timeMs>1299)throw Error('timeMs must be an integer from 0 to 1299');for(const key of ['xArcmin','yArcmin'])if(key in input&&(!Number.isFinite(input[key])||Math.abs(input[key])>11.85))throw Error('Invalid '+key);if('responseView'in input&&!['full','optotype'].includes(input.responseView))throw Error('Invalid responseView');if('colorScale'in input&&!['independent','shared'].includes(input.colorScale))throw Error('Invalid colorScale');if(!result||busy)throw Error('Wait for the simulation to finish');if('xArcmin'in input)probe.x=input.xArcmin;if('yArcmin'in input)probe.y=input.yArcmin;if(input.responseView){view.response=input.responseView;$('response-view').value=view.response;}if(input.colorScale){view.scale=input.colorScale;$('color-scale').value=view.scale;}setTime(input.timeMs);drawAll();return read();}});
})();
