'use strict';
const $=id=>document.getElementById(id),MODEL=AOSLOModel;
const defaults={rate:30,hold:1,gain:1,D:40,centering:10,size:5,contrast:1,orientation:'right',controller:'ideal',matchMean:false,seed:7};
let settings={...defaults},result=null,worker=null,computeTimer=null,busy=false,time=33,playing=false,lastWall=0,playTime=33,frameId=null,probe={x:1.35,y:.75};
let view={response:'full',scale:'independent',axis:'x',traceScale:'normalized'};
function range(id,label,min,max,step,unit,note=''){return `<div class="control"><label for="${id}">${label}<output id="out-${id}">${settings[id]}${unit}</output></label><input id="${id}" type="range" min="${min}" max="${max}" step="${step}" value="${settings[id]}" data-unit="${unit}">${note?`<small>${note}</small>`:''}</div>`;}
function select(id,label,options){return `<div class="control"><label for="${id}">${label}</label><select id="${id}">${options.map(([v,l])=>`<option value="${v}" ${settings[id]===v?'selected':''}>${l}</option>`).join('')}</select></div>`;}
function renderControls(){
 $('parameters').innerHTML=range('rate','Flicker rate',5,120,1,' Hz')+range('hold','Hold duration',1,200,1,' ms')+range('gain','Stabilization gain',-1,2,.05,'','0 = natural slip · 1 = stabilized')+`<label class="check"><input id="matchMean" type="checkbox" ${settings.matchMean?'checked':''}>Match mean luminance</label>`;
 $('extra-parameters').innerHTML=range('size','E height',3,15,.5,'′','Stroke width = E height / 5')+select('orientation','E points',[['right','Right'],['up','Up'],['left','Left'],['down','Down']])+range('D','Eye diffusion',0,100,1,' arcmin²/s')+range('centering','Centering strength',0,40,1,' /s','0 = free drift · stronger = tighter fixation')+range('contrast','E contrast',0,1,.05,'')+select('controller','Compensation timing',[['ideal','Every 1 ms · ideal gain'],['frame','At flash onset · then held']]);
 document.querySelectorAll('aside input,aside select').forEach(el=>el.addEventListener('input',()=>{settings[el.id]=el.type==='checkbox'?el.checked:el.tagName==='SELECT'?el.value:+el.value;if($('out-'+el.id))$('out-'+el.id).textContent=el.value+el.dataset.unit;updateGain();requestCompute();}));updateGain();
}
function updateGain(){const g=settings.gain,label=g===1?'Full stabilization':g===0?'Natural retinal slip':g<0?'Amplified retinal slip':g>1?'Overstabilized, reversed slip':'Partial stabilization';$('gain-explanation').innerHTML=`<strong>${label}</strong><br>Ideal retinal motion = (${g.toFixed(2)} − 1) × eye motion.${settings.controller==='frame'?'<br>Held commands leave additional between-flash error.':''}`;}
function requestCompute(immediate=false){pause();clearTimeout(computeTimer);if(worker){worker.terminate();worker=null;}busy=true;$('movies').classList.add('busy');$('play').disabled=true;$('compute-status').classList.remove('error');$('compute-status').textContent=result?'Settings changed · computing a new movie…':'Preparing 1,300 one-millisecond frames…';computeTimer=setTimeout(compute,immediate?0:250);}
function compute(){worker=new Worker('aoslo-worker.js?v=3');worker.onmessage=e=>{const d=e.data;if(d.type==='progress')$('compute-status').innerHTML=`<progress max="100" value="${d.percent}"></progress>${d.label}`;if(d.type==='error'){fail(d.message);return;}if(d.type==='result'){result=d.result;busy=false;$('movies').classList.remove('busy');$('play').disabled=false;$('compute-status').textContent='Ready · causal M/P convolution · 80 × 80 positions · 1 ms samples';time=Math.min(time,result.T-1);playTime=time;worker.terminate();worker=null;drawAll();document.dispatchEvent(new CustomEvent('aoslo-ready'));}};worker.onerror=e=>fail(e.message||'Unable to compute the movie');worker.postMessage({...settings});}
function fail(message){busy=false;$('movies').classList.remove('busy');$('compute-status').classList.add('error');$('compute-status').textContent='Simulation could not finish: '+message+'. Change a setting to retry.';if(worker)worker.terminate();worker=null;$('play').disabled=!result;document.dispatchEvent(new CustomEvent('aoslo-error',{detail:message}));}
function pause(){playing=false;cancelAnimationFrame(frameId);$('play').textContent='▶ Play';}
function setTime(t){pause();time=Math.max(0,Math.min(1299,Math.round(t)));playTime=time;drawFrames(time,time);drawTimeMarkers();}
function start(){if(!result||busy)return;if(time>=result.T-1){time=0;playTime=0;}playing=true;lastWall=performance.now();$('play').textContent='Ⅱ Pause';frameId=requestAnimationFrame(tick);}
function tick(now){if(!playing)return;const dt=now-lastWall;lastWall=now;const old=time;playTime+=Math.min(dt,100)*+$('speed').value;if(playTime>=result.T){if($('loop').checked){playTime=0;time=0;}else{setTime(result.T-1);return;}}time=Math.floor(playTime);if(time!==old){drawFrames(old<=time?old+1:time,time);drawTimeMarkers();}frameId=requestAnimationFrame(tick);}
function mapScale(type){if(type==='input')return result.peak;const key=view.response==='optotype'?'opt':'max';const m=result[key+'M'],p=result[key+'P'];return Math.max(1e-9,view.scale==='shared'?Math.max(m,p):type==='M'?m:p);}
function valueAt(type,t,p){const value=(type==='input'?result.input:result[type])[t*result.N*result.N+p];return type!=='input'&&view.response==='optotype'?value-result['bg'+type][t]:value;}
function color(value,max,type){if(type==='input'){const c=Math.round(255*Math.max(0,Math.min(1,value/max)));return [c,c,c];}const v=Math.max(-1,Math.min(1,value/max)),z=Math.abs(v),edge=v>=0?[216,96,40]:[32,101,172],mid=[245,247,249];return mid.map((a,i)=>Math.round(a+(edge[i]-a)*z));}
const small=document.createElement('canvas');small.width=80;small.height=80;const smallCtx=small.getContext('2d');
function drawMovie(type,from,to){const c=$('movie-'+type),ctx=c.getContext('2d'),N=result.N,P=N*N,max=mapScale(type),img=smallCtx.createImageData(N,N),span=to-from+1;for(let p=0;p<P;p++){let value=0;for(let t=from;t<=to;t++)value+=valueAt(type,t,p);const rgb=color(value/span,max,type);img.data.set([...rgb,255],4*p);}smallCtx.putImageData(img,0,0);const w=c.clientWidth||320;c.width=Math.round(w*2);c.height=c.width;ctx.imageSmoothingEnabled=false;ctx.drawImage(small,0,0,c.width,c.height);const x=(probe.x/result.FOV+.5)*c.width,y=(probe.y/result.FOV+.5)*c.height;ctx.strokeStyle=type==='input'?'#e98043':'#23354da0';ctx.lineWidth=2;ctx.setLineDash([5,6]);ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,c.height);ctx.moveTo(0,y);ctx.lineTo(c.width,y);ctx.stroke();ctx.setLineDash([]);ctx.strokeStyle='#f09a62';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(c.width*.07,c.height*.92);ctx.lineTo(c.width*(.07+2/result.FOV),c.height*.92);ctx.stroke();ctx.fillStyle=type==='input'?'#e98043':'#344356';ctx.font=`${Math.round(w*.08)}px -apple-system,sans-serif`;ctx.fillText('2′',c.width*.07,c.height*.88);c.setAttribute('aria-label',`${type==='input'?'Retinal input':type+' model response'} at ${time} ms. Probe x ${probe.x.toFixed(1)}, y ${probe.y.toFixed(1)} arcmin.`);}
function drawFrames(from=time,to=time){if(!result)return;from=Math.max(0,from);to=Math.max(from,to);for(const type of ['input','M','P'])drawMovie(type,from,to);$('time').value=time;$('time-value').textContent=time+' ms';$('frame-status').textContent=playing&&to>from?`Playback average · ${from}–${to} ms`:result.gate[time]>0?'Flash ON · exact 1 ms sample':time>=1000?'Stimulus ended · response tail':'Flash OFF · exact 1 ms sample';$('input-scale').textContent='0 → '+result.peak.toFixed(result.peak>2?1:0);for(const type of ['M','P'])$(''+type+'-scale').textContent='±'+mapScale(type).toPrecision(3)+' a.u.';}
function drawAll(){if(!result)return;if(typeof snapProbe==='function')snapProbe();drawFrames();$('figure-note').textContent=`24 × 24 arcmin field · Click a movie to choose a cell and slice. Blue = negative, white = zero, orange = positive response. ${view.scale==='independent'?'M/P colors use independent scales; compare numbers for amplitudes.':'M and P share one numerical color scale.'} Scales stay fixed across this movie.`;$('stats').innerHTML=`<div class="stat"><strong>${(result.duty*100).toFixed(1)}%</strong><span>Illuminated time</span></div><div class="stat"><strong>${result.onsets.length} flashes</strong><span>Scheduled in 1,000 ms</span></div><div class="stat"><strong>${result.settings.gain.toFixed(2)}</strong><span>Stabilization gain</span></div>`;if(typeof drawAnalysis==='function')drawAnalysis();}

$('play').addEventListener('click',()=>playing?pause():start());$('time').addEventListener('input',e=>setTime(+e.target.value));$('back').addEventListener('click',()=>setTime(time-1));$('forward').addEventListener('click',()=>setTime(time+1));$('flash').addEventListener('click',()=>{if(result)setTime(result.onsets.find(t=>t>time)??result.onsets[0]);});$('speed').addEventListener('change',()=>{playTime=time;lastWall=performance.now();});$('response-view').addEventListener('change',e=>{view.response=e.target.value;drawAll();});$('color-scale').addEventListener('change',e=>{view.scale=e.target.value;drawAll();});$('reset').addEventListener('click',()=>{settings={...defaults};time=33;probe={x:1.35,y:.75};renderControls();requestCompute(true);});document.querySelectorAll('[data-preset]').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.preset==='aoslo'){settings.rate=30;settings.hold=1;}else settings.hold=Math.ceil(1000/settings.rate);renderControls();requestCompute(true);}));for(const type of ['input','M','P'])$('movie-'+type).addEventListener('click',e=>{if(!result)return;const rect=e.currentTarget.getBoundingClientRect();probe.x=((e.clientX-rect.left)/rect.width-.5)*result.FOV;probe.y=((e.clientY-rect.top)/rect.height-.5)*result.FOV;drawAll();});
renderControls();requestCompute(true);
